// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ2NHMxPfhxStWTNWiS2susFKSWYbwBe0',
    appId: '1:197535798478:web:22eb9425663ad13a9eec9f',
    messagingSenderId: '197535798478',
    projectId: 'ai-chatbot-32ca1',
    authDomain: 'ai-chatbot-32ca1.firebaseapp.com',
    storageBucket: 'ai-chatbot-32ca1.appspot.com',
    measurementId: 'G-RS4R7DJD2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLzeZpcxswLa2xB0OXd7wURk2Al3X3Ljw',
    appId: '1:197535798478:android:763891a4f8f935f89eec9f',
    messagingSenderId: '197535798478',
    projectId: 'ai-chatbot-32ca1',
    storageBucket: 'ai-chatbot-32ca1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJhXlAH4eQHLg99ZXLpkuw3h4OXjkv4F0',
    appId: '1:197535798478:ios:811d40b37638f8809eec9f',
    messagingSenderId: '197535798478',
    projectId: 'ai-chatbot-32ca1',
    storageBucket: 'ai-chatbot-32ca1.appspot.com',
    androidClientId: '197535798478-p7vcebq7mbq1uqkokqe0hmponj64h07q.apps.googleusercontent.com',
    iosClientId: '197535798478-rpduj8qb3ckrfvkju7oi3bfmrtbfo5kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.zahrachatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJhXlAH4eQHLg99ZXLpkuw3h4OXjkv4F0',
    appId: '1:197535798478:ios:811d40b37638f8809eec9f',
    messagingSenderId: '197535798478',
    projectId: 'ai-chatbot-32ca1',
    storageBucket: 'ai-chatbot-32ca1.appspot.com',
    androidClientId: '197535798478-p7vcebq7mbq1uqkokqe0hmponj64h07q.apps.googleusercontent.com',
    iosClientId: '197535798478-rpduj8qb3ckrfvkju7oi3bfmrtbfo5kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.zahrachatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ2NHMxPfhxStWTNWiS2susFKSWYbwBe0',
    appId: '1:197535798478:web:c5c925526c4b830e9eec9f',
    messagingSenderId: '197535798478',
    projectId: 'ai-chatbot-32ca1',
    authDomain: 'ai-chatbot-32ca1.firebaseapp.com',
    storageBucket: 'ai-chatbot-32ca1.appspot.com',
    measurementId: 'G-9YTGLLK1D4',
  );
}
